volumes:
  share: {}
  transmission: {}

services:
  base:
    build:
      context: .
    image: base_media

  samba:
    build:
      context: .
      dockerfile: SambaDockerfile
    restart: always
    ports:
      - 445:445
    volumes:
      - share:/share
    environment:
      - USER=${USER:-mediauser}
      - PASS=${PASSWORD:-mediapass}
      - UID=${LOCAL_UID:-1000}
      - GID=${LOCAL_GID:-1000}
    depends_on:
      - base

  transmission:
    build:
      context: .
      dockerfile: TransmissionDockerfile
    restart: always
    ports:
      - 9091:9091
    volumes:
      - share:/share
      - transmission:/var/lib/transmission-daemon
    depends_on:
      - base
    environment:
      - TRANSMISSION_WEB_HOME=/combustion/combustion-release
